name: CI/CD Springboot

on:
    push: 
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do código
              uses: actions/checkout@v4
            
            - name: Configurar JDk
              uses: actions/setup-java@v4
              with:
                java-version: "21"
                distribution: "temurin"
            
            - name: instalar dependências e rodar teste
              run: mvn clean install

            - name: Gerar .jar
              run: mvn package -DskipTests
            
            - name: Uploado do .jar
              uses: actions/upload-artifact@v4
              with:
                name: app-jar
                path: target/*.jar